[package]
name = "odesli"
version = "0.1.0"
edition = "2021"
authors = ["Akshett Rai Jindal"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Propheci/odesli-rs"
description = "CLI tool to help interact with odesli API"
keywords = ["odesli", "music"]

[dependencies]
async-trait = "0.1.83"
clap = { version = "4.5.23", features = ["derive"] }
lazy_static = "1.5.0"
odesli-rs = { path = "../lib", features = ["clap"] }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
strum = { version = "0.25.0", features = ["derive"] }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
