[package]
name = "odesli-rs"
version = "1.0.0"
edition = "2021"
authors = ["Akshett Rai Jindal"]

[dependencies]
reqwest = { version = "0.11.22", features = ["gzip", "json", "deflate"] }
serde = { version = "1.0.189", features = ["derive"] }
